#+title: LeanMD run log
#+author: Christian Asch

Session log of actual =jube= invocations against LeanMD's =bench.yml=
on Kabré: what was submitted, whether it finished, and anything
unusual. See [[file:bench.yml][bench.yml]] for the benchmark definition itself
and [[file:../README.org][README.org]] for how the pieces of this repo fit together.

Entries dated before [2026-08-07] were written when this file was
=runs/leanmd.org= and the benchmark definition was =bench-leanmd.yml= at the
repo root. Their paths are left as they were recorded. One ChaNGa session
that had been logged here, [2026-07-24 Fri], moved to [[file:../changa/runs.org][changa/runs.org]] in that
same reorganization.

* [2026-07-23 Thu] 

I've installed and added jube to the PATH variable

#+BEGIN_SRC bash :session *Shell* :results output :exports both :async yes
  jube --version
#+END_SRC

#+RESULTS:
: JUBE, version 2.7.1

Let's check our queue just in case

#+BEGIN_SRC bash :session *Shell* :results output :exports both :async yes
  squeue -u casch
#+END_SRC

#+RESULTS:
: JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)

We first run the base version of the benchmarks, that is, without
using projections.

#+BEGIN_SRC bash :session *Shell* :results output :exports both :async yes
  jube run ../bench-leanmd.yml \
       --include-path /data/casch/JUBE/platform/slurm \
       --tag base
#+END_SRC

#+RESULTS:
#+begin_example
######################################################################
# benchmark: leanmd
# id: 0
#
#
######################################################################

Running workpackages (#=done, 0=wait, E=error):
000000000000000000000000000000000000000000000000000000000000 (  0/  3)

  |    stepname | all | open | wait | error | done |
  |-------------|-----|------|------|-------|------|
  | run-program |   3 |    0 |    3 |     0 |    0 |

>>>> Benchmark information and further useful commands:
>>>>       id: 0
>>>>   handle: ../leanmd_bench
>>>>      dir: ../leanmd_bench/000000
>>>> continue: jube continue ../leanmd_bench --id 0
>>>>  analyse: jube analyse ../leanmd_bench --id 0
>>>>   result: jube result ../leanmd_bench --id 0
>>>>     info: jube info ../leanmd_bench --id 0
>>>>      log: jube log ../leanmd_bench --id 0
######################################################################
#+end_example

#+BEGIN_SRC bash :session *Shell* :results output :exports both :async yes
  jube continue ../leanmd_bench --id 0
#+END_SRC

#+RESULTS:
#+begin_example
######################################################################
# benchmark: leanmd
# id: 0
#
#
######################################################################

Running workpackages (#=done, 0=wait, E=error):
########################################00000000000000000000 (  2/  3)

  |    stepname | all | open | wait | error | done |
  |-------------|-----|------|------|-------|------|
  | run-program |   3 |    0 |    1 |     0 |    2 |

>>>> Benchmark information and further useful commands:
>>>>       id: 0
>>>>   handle: ../leanmd_bench
>>>>      dir: ../leanmd_bench/000000
>>>> continue: jube continue ../leanmd_bench --id 0
>>>>  analyse: jube analyse ../leanmd_bench --id 0
>>>>   result: jube result ../leanmd_bench --id 0
>>>>     info: jube info ../leanmd_bench --id 0
>>>>      log: jube log ../leanmd_bench --id 0
######################################################################
#+end_example

There is one job stuck because of resources, that's okay for now

#+BEGIN_SRC bash :session *Shell* :results output :exports both :async yes
  squeue -u casch
#+END_SRC

#+RESULTS:
: JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
:             595960 kura-wide leanmd_r    casch PD       0:00      4 (Resources)
:             595958 kura-wide leanmd_r    casch  R       0:19      1 kura-1d.cnca
:             595959 kura-wide leanmd_r    casch  R       0:19      2 kura-2a.cnca,kura-2b.cnca

Base version works. Now that we know that the base version is
working, we'll run the Projections version.

#+BEGIN_SRC bash :session *Shell* :results output :exports both :async yes
  jube run ../bench-leanmd.yml \
       --include-path /data/casch/JUBE/platform/slurm \
       --tag tracing
#+END_SRC

#+RESULTS:
#+begin_example
######################################################################
# benchmark: leanmd
# id: 1
#
#
######################################################################

Running workpackages (#=done, 0=wait, E=error):
000000000000000000000000000000000000000000000000000000000000 (  0/  3)

  |    stepname | all | open | wait | error | done |
  |-------------|-----|------|------|-------|------|
  | run-program |   3 |    0 |    3 |     0 |    0 |

>>>> Benchmark information and further useful commands:
>>>>       id: 1
>>>>   handle: ../leanmd_bench
>>>>      dir: ../leanmd_bench/000001
>>>> continue: jube continue ../leanmd_bench --id 1
>>>>  analyse: jube analyse ../leanmd_bench --id 1
>>>>   result: jube result ../leanmd_bench --id 1
>>>>     info: jube info ../leanmd_bench --id 1
>>>>      log: jube log ../leanmd_bench --id 1
######################################################################
#+end_example

#+BEGIN_SRC bash :session *Shell* :results output :exports both :async yes
  jube continue ../leanmd_bench --id 1
#+END_SRC

#+RESULTS:
#+begin_example
######################################################################
# benchmark: leanmd
# id: 1
#
#
######################################################################

Running workpackages (#=done, 0=wait, E=error):
000000000000000000000000000000000000000000000000000000000000 (  0/  3)

  |    stepname | all | open | wait | error | done |
  |-------------|-----|------|------|-------|------|
  | run-program |   3 |    0 |    3 |     0 |    0 |

>>>> Benchmark information and further useful commands:
>>>>       id: 1
>>>>   handle: ../leanmd_bench
>>>>      dir: ../leanmd_bench/000001
>>>> continue: jube continue ../leanmd_bench --id 1
>>>>  analyse: jube analyse ../leanmd_bench --id 1
>>>>   result: jube result ../leanmd_bench --id 1
>>>>     info: jube info ../leanmd_bench --id 1
>>>>      log: jube log ../leanmd_bench --id 1
######################################################################
#+end_example

It seems like this is stuck

#+BEGIN_SRC bash :results output :exports both
  cat ../leanmd_bench/000001/000000_run-program/work/job.err
#+END_SRC

#+RESULTS:
#+begin_example
+ export OMP_NUM_THREADS=1
+ OMP_NUM_THREADS=1
+ module purge
++ /opt/Modules/3.2.10/bin/modulecmd bash purge
+ eval MODULEPATH=/opt/libs/modulefiles:/opt/tools/modulefiles:/opt/compilers/modulefiles:/opt/python/modulefiles:/opt/bioinf/modulefiles ';export' 'MODULEPATH;'
++ MODULEPATH=/opt/libs/modulefiles:/opt/tools/modulefiles:/opt/compilers/modulefiles:/opt/python/modulefiles:/opt/bioinf/modulefiles
++ export MODULEPATH
+ module load mpich/3.1.4-gcc-9.3.0 gcc/9.3.0
++ /opt/Modules/3.2.10/bin/modulecmd bash load mpich/3.1.4-gcc-9.3.0 gcc/9.3.0
+ eval CPATH=/opt/compilers/gcc-9.3.0/include:/opt/tools/mpich-3.1.4-gcc-9.3.0/include ';export' 'CPATH;INCLUDE=/opt/compilers/gcc-9.3.0/include' ';export' 'INCLUDE;INFOPATH=/opt/compilers/gcc-9.3.0/share/info' ';export' 'INFOPATH;LD_LIBRARY_PATH=/opt/compilers/gcc-9.3.0/lib64:/opt/compilers/gcc-9.3.0/lib:/opt/tools/mpich-3.1.4-gcc-9.3.0/lib' ';export' 'LD_LIBRARY_PATH;LIBRARY_PATH=/opt/compilers/gcc-9.3.0/lib64:/opt/compilers/gcc-9.3.0/lib:/opt/tools/mpich-3.1.4-gcc-9.3.0/lib' ';export' 'LIBRARY_PATH;LOADEDMODULES=mpich/3.1.4-gcc-9.3.0:gcc/9.3.0' ';export' 'LOADEDMODULES;MANPATH=/opt/compilers/gcc-9.3.0/share/man:/opt/tools/mpich-3.1.4-gcc-9.3.0/share/man/:/usr/share/man' ';export' 'MANPATH;MPI_BIN=/opt/tools/mpich-3.1.4-gcc-9.3.0/bin' ';export' 'MPI_BIN;MPI_FORTRAN_MOD_DIR=/opt/tools/mpich-3.1.4-gcc-9.3.0/lib' ';export' 'MPI_FORTRAN_MOD_DIR;MPI_HOME=/opt/tools/mpich-3.1.4-gcc-9.3.0' ';export' 'MPI_HOME;MPI_INC=/opt/tools/mpich-3.1.4-gcc-9.3.0/include' ';export' 'MPI_INC;MPI_LIB=/opt/tools/mpich-3.1.4-gcc-9.3.0/lib' ';export' 'MPI_LIB;MPI_MAN=/opt/tools/mpich-3.1.4-gcc-9.3.0/share/man' ';export' 'MPI_MAN;PATH=/opt/compilers/gcc-9.3.0/bin:/opt/tools/mpich-3.1.4-gcc-9.3.0/bin:/home/casch/.local/bin:/usr/bin:/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin' ';export' 'PATH;_LMFILES_=/opt/tools/modulefiles/mpich/3.1.4-gcc-9.3.0:/opt/compilers/modulefiles/gcc/9.3.0' ';export' '_LMFILES_;'
++ CPATH=/opt/compilers/gcc-9.3.0/include:/opt/tools/mpich-3.1.4-gcc-9.3.0/include
++ export CPATH
++ INCLUDE=/opt/compilers/gcc-9.3.0/include
++ export INCLUDE
++ INFOPATH=/opt/compilers/gcc-9.3.0/share/info
++ export INFOPATH
++ LD_LIBRARY_PATH=/opt/compilers/gcc-9.3.0/lib64:/opt/compilers/gcc-9.3.0/lib:/opt/tools/mpich-3.1.4-gcc-9.3.0/lib
++ export LD_LIBRARY_PATH
++ LIBRARY_PATH=/opt/compilers/gcc-9.3.0/lib64:/opt/compilers/gcc-9.3.0/lib:/opt/tools/mpich-3.1.4-gcc-9.3.0/lib
++ export LIBRARY_PATH
++ LOADEDMODULES=mpich/3.1.4-gcc-9.3.0:gcc/9.3.0
++ export LOADEDMODULES
++ MANPATH=/opt/compilers/gcc-9.3.0/share/man:/opt/tools/mpich-3.1.4-gcc-9.3.0/share/man/:/usr/share/man
++ export MANPATH
++ MPI_BIN=/opt/tools/mpich-3.1.4-gcc-9.3.0/bin
++ export MPI_BIN
++ MPI_FORTRAN_MOD_DIR=/opt/tools/mpich-3.1.4-gcc-9.3.0/lib
++ export MPI_FORTRAN_MOD_DIR
++ MPI_HOME=/opt/tools/mpich-3.1.4-gcc-9.3.0
++ export MPI_HOME
++ MPI_INC=/opt/tools/mpich-3.1.4-gcc-9.3.0/include
++ export MPI_INC
++ MPI_LIB=/opt/tools/mpich-3.1.4-gcc-9.3.0/lib
++ export MPI_LIB
++ MPI_MAN=/opt/tools/mpich-3.1.4-gcc-9.3.0/share/man
++ export MPI_MAN
++ PATH=/opt/compilers/gcc-9.3.0/bin:/opt/tools/mpich-3.1.4-gcc-9.3.0/bin:/home/casch/.local/bin:/usr/bin:/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
++ export PATH
++ _LMFILES_=/opt/tools/modulefiles/mpich/3.1.4-gcc-9.3.0:/opt/compilers/modulefiles/gcc/9.3.0
++ export _LMFILES_
+ export LD_LIBRARY_PATH=/data/casch/charm-stuff/charm-benchmarks/deps/prefix/lib:/opt/compilers/gcc-9.3.0/lib64:/opt/compilers/gcc-9.3.0/lib:/opt/tools/mpich-3.1.4-gcc-9.3.0/lib
+ LD_LIBRARY_PATH=/data/casch/charm-stuff/charm-benchmarks/deps/prefix/lib:/opt/compilers/gcc-9.3.0/lib64:/opt/compilers/gcc-9.3.0/lib:/opt/tools/mpich-3.1.4-gcc-9.3.0/lib
+ export PKG_CONFIG_PATH=/data/casch/charm-stuff/charm-benchmarks/deps/prefix/lib/pkgconfig:
+ PKG_CONFIG_PATH=/data/casch/charm-stuff/charm-benchmarks/deps/prefix/lib/pkgconfig:
+ export PATH=/data/casch/charm-stuff/charm-benchmarks/deps/prefix/bin:/opt/compilers/gcc-9.3.0/bin:/opt/tools/mpich-3.1.4-gcc-9.3.0/bin:/home/casch/.local/bin:/usr/bin:/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
+ PATH=/data/casch/charm-stuff/charm-benchmarks/deps/prefix/bin:/opt/compilers/gcc-9.3.0/bin:/opt/tools/mpich-3.1.4-gcc-9.3.0/bin:/home/casch/.local/bin:/usr/bin:/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
+ sed 4d Makefile -i
+ sed 4iCHARMBASE=/data/casch/charm-stuff/charm-benchmarks/deps/prefix/charm-projections Makefile -i
++ pkgconf --libs papi
+ make projections 'OPTS=-I/data/casch/charm-stuff/charm-benchmarks/deps/prefix/include -L/data/casch/charm-stuff/charm-benchmarks/deps/prefix/lib -lpapi ' -j
+ JUBE_ERR_CODE=0
+ '[' 0 -ne 0 ']'
+ mpirun -np 20 ./leanmd.prj 10 10 10 100 20 20 +logsize 32000000
#+end_example

* [2026-08-14 Fri] LeanMD does not run on the current Charm++

Attempted the first traced LeanMD run since the SMP Charm++ rebuild, as the
generality check for the CCGrid paper. It does not run, and has probably
not run since that rebuild.

LeanMD segfaults in =ConverseInit=, inside =MPI_Comm_dup_with_info=,
before any application code executes. Isolated by controlled comparison,
one variable at a time:

| Configuration                                     | Result             |
|---------------------------------------------------+--------------------|
| Instrumented LeanMD, 2 hosts, 8 ranks             | segfault           |
| Pristine upstream LeanMD, same                    | identical segfault |
| Pristine, 1 host, 4 ranks                         | identical segfault |
| Pristine against =charm-changa-projections=       | identical segfault |
| Pristine with =+ppn 1= (this Charm++ is SMP)      | identical segfault |
| Plain =leanmd= target on =charm-base=, no tracing | identical segfault |
| ChaNGa on =charm-changa-projections=              | runs normally      |

Jobs 600496 through 600501. So it is not the instrumentation, not the node
count, not the Charm++ variant, not the missing =+ppn=, and not tracing.
Charm++ is sound: ChaNGa runs on the same build.

The instrumentation itself builds clean and is committed to
=caschb/leanmd= branch =thesis-instrumentation=. It has never produced a
trace, and the commit message says so.

Next step for whoever picks this up: bisect Charm++ versions, or build
LeanMD against something close to the CARLA-era Charm++. The traces behind
that paper carry job IDs around 198000 against today's 600000. Do not
start by re-examining the instrumentation -- it is excluded by the
pristine-source rows above. See =docs/design-notes.org=, "LeanMD does not
currently run on this Charm++".

* [2026-08-14 Fri] Follow-up: the segfault above was a local test-script bug

The entry above is wrong and is left as written, per this file's own rule
against rewriting a dated record; this is the correction.

Every configuration in that elimination table was launched from ad hoc
scripts, not =bench.yml=, and every one of those scripts loaded
=gcc/12.4.0 openmpi/4.0.5=. =deps/prefix='s Charm++ is built against
=mpich/3.1.4-gcc-9.3.0= (=bench.yml= loads it correctly; grep the =module
load= line in either program's =bench.yml=). MPICH and OpenMPI are
ABI-incompatible, so launching an MPICH-linked Charm++ under OpenMPI's
=mpirun= was expected to crash exactly where it did, in
=MPI_Comm_dup_with_info=, on the first real MPI call -- and to do so
identically across every variation, since none of the six varied the one
thing that mattered. Rebuilt and reran under the correct module (job
600508): LeanMD ran 20 steps, passed its own energy-conservation check,
and exited cleanly. ChaNGa's earlier "runs normally" control was not
special -- it happened to always be launched through =bench.yml=, and
so happened to always get the right module.

Two further, real bugs surfaced once LeanMD was actually running -- see
=docs/design-notes.org=, "the =LeanMD does not run= segfault was a local
test-script bug" -- both in the domain-CSV flush, both silent (a
=CkExit()= race that dropped the flush's reduction with no error, and a
macro that never reached the =.ci= file's own translation step so the
flush code was never compiled in at all). Fixed in the same session; a
clean rerun (job 600519) wrote all 1280 rows to =leanmd.domain.csv= and
exited normally. LeanMD is unblocked as the generality check.
